cub: 
  db_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_db/sd-cub-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: null

  db_35000_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_db_5shot/sd-cub-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: null

  ti_35000_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: null
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_5shot/sd-cub-model-lora-rank10/learned_embeds-steps-last.bin"

  ti_db_35000_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-cub-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-cub-model-lora-rank10/learned_embeds-steps-last.bin"

  ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: null
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti/sd-cub-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti5000:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10/checkpoint-5000/pytorch_model.bin"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10/learned_embeds-steps-5000.bin"

  db_ti15000:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10/checkpoint-15000/pytorch_model.bin"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10/learned_embeds-steps-15000.bin"
  db_ti25000:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10/checkpoint-25000/pytorch_model.bin"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10/learned_embeds-steps-25000.bin"


  db_ti35000:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10/checkpoint-35000/pytorch_model.bin"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10/learned_embeds-steps-35000.bin"

  db_ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10/checkpoint-35000/pytorch_model.bin"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10/learned_embeds-steps-35000.bin"

  db_ti_latest_imb_0.1:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.1/sd-cub-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.1/sd-cub-model-lora-rank10/learned_embeds-steps-last.bin"

  db_ti_latest_imb_0.05:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.05/sd-cub-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.05/sd-cub-model-lora-rank10/learned_embeds-steps-last.bin"

  db_ti_latest_imb_0.01:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.01/sd-cub-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.01/sd-cub-model-lora-rank10/learned_embeds-steps-last.bin"

  db_ti_latest_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-cub-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-cub-model-lora-rank10/learned_embeds-steps-last.bin"


  db_ti_latest_10shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_10shot/sd-cub-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_10shot/sd-cub-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest_e100:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10-e100/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-cub-model-lora-rank10-e100/learned_embeds-steps-last.bin"
    
flower: 
  ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: null
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti/sd-aircraft-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-flower-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-flower-model-lora-rank10/learned_embeds-steps-last.bin" 
  db_ti_latest_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-flower-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-flower-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest_imb_0.1:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.1/sd-flower-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.1/sd-flower-model-lora-rank10/learned_embeds-steps-last.bin"

  db_ti_latest_imb_0.05:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.05/sd-flower-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.05/sd-flower-model-lora-rank10/learned_embeds-steps-last.bin"
    
  db_ti_latest_imb_0.01:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.01/sd-flower-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/imbalanced_finetune_ti_db/0.1/sd-flower-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest_10shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_10shot/sd-flower-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_10shot/sd-flower-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-flower-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-flower-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest_1shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_1shot/sd-flower-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_1shot/sd-flower-model-lora-rank10/learned_embeds-steps-last.bin"

aircraft: 
  ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: null
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti/sd-aircraft-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-aircraft-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-aircraft-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest_e100:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-aircraft-model-lora-rank10-e100/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-aircraft-model-lora-rank10-e100/learned_embeds-steps-last.bin"
  db_ti_latest_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-aircraft-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-aircraft-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest_10shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_10shot/sd-aircraft-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_10shot/sd-aircraft-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-aircraft-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-aircraft-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest_1shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_1shot/sd-aircraft-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_1shot/sd-aircraft-model-lora-rank10/learned_embeds-steps-last.bin"
chest:
  db_ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-chest-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-chest-model-lora-rank10/learned_embeds-steps-last.bin"
car:
  ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: null
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti/sd-car-model-lora-rank10/learned_embeds-steps-last.bin"
  db_ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-car-model-ti+lora/checkpoint-30000/pytorch_model.bin"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-car-model-ti+lora/learned_embeds-steps-30000.bin"
  db_ti_latest_e100:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-car-model-lora-rank10-e100/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-car-model-lora-rank10-e100/learned_embeds-steps-last.bin"
food:
  db_ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-food-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-food-model-lora-rank10/learned_embeds-steps-last.bin"
pet:
  db_ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-pet-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-pet-model-lora-rank10/learned_embeds-steps-5000.bin"
dog:
  ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: null
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti/sd-dog-model-lora-rank10/learned_embeds-steps-last.bin"
  
  db_ti_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-dog-model-lora-rank10-e100/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-dog-model-lora-rank10-e100/learned_embeds-steps-last.bin"

  db_ti_latest_e100:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-dog-model-lora-rank10-e100/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db/sd-dog-model-lora-rank10-e100/learned_embeds-steps-last.bin"
  db_ti_latest_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-dog-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_ti_db_5shot/sd-dog-model-lora-rank10/learned_embeds-steps-last.bin"
caltech:
  db_latest_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_db_5shot/sd-caltech-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: null
pascal:
  db_latest_5shot:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "/data/zhicai/code/Diff-Mix/outputs/finetune_model/finetune_db_5shot/sd-pascal-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: null

  db_latest:
    model_path: "runwayml/stable-diffusion-v1-5"
    lora_path: "outputs/finetune_model/finetune_db/sd-pascal-model-lora-rank10/pytorch_lora_weights.safetensors"
    embed_path: null